/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;
import java.awt.Color;
import javax.swing.JTable;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import modelo.Etapa;
import modelo.ResultadoEtapa;
import logica.MotorAsignacion;

public class Ventana extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventana.class.getName());

    /**
     * Creates new form Ventana
     */
        public Ventana() {
            initComponents();
            this.getContentPane().setBackground(Color.decode("#1F911F"));
        }
        
        private JTable crearTabla(ResultadoEtapa r) {

            int filas = r.S.length;
            int cols = r.F[0].length;

            String[] columnas = new String[cols + 3];

            columnas[0] = "S";

            for (int j = 0; j < cols; j++) {
                columnas[j + 1] = "D=" + r.D[0][j];
            }

            columnas[cols + 1] = "F*";
            columnas[cols + 2] = "d*";

            Object[][] data = new Object[filas][cols + 3];

            for (int i = 0; i < filas; i++) {

                data[i][0] = r.S[i];

                int best = argMin(r.F[i]);

                for (int j = 0; j < cols; j++) {
                    if (Double.isInfinite(r.F[i][j])) data[i][j + 1] = "X";
                    else data[i][j + 1] = String.format("%.1f", r.F[i][j]);
                }

                data[i][cols + 1] = String.format("%.1f", r.F[i][best]);
                data[i][cols + 2] = r.D[i][best];
            }

            DefaultTableModel model = new DefaultTableModel(data, columnas);
            JTable table = new JTable(model);

            return table;
        }
       
        private int argMin(double[] row) {
            int idx = 0;
            double min = Double.POSITIVE_INFINITY;

            for (int i = 0; i < row.length; i++) {
                if (row[i] < min) {
                    min = row[i];
                    idx = i;
                }
            }
            return idx;
        }
        
        private int sumaPosteriores(int[] mins,int desde){
            int s=0;
            for(int i=desde+1;i<mins.length;i++) s+=mins[i];
            return s;
        }
        
        private Object[][] interpretar(ResultadoEtapa[] rs, Etapa[] info, int macetas){

            int n = rs.length;

            Object[][] tabla = new Object[n+1][4];

            int sumaPersonas = 0;
            double sumaTiempo = 0;

            for(int k=0;k<n;k++){

                ResultadoEtapa r = rs[k];
                Etapa e = info[k];

                // tomamos la última fila (ya optimizada por DP)
                int fila = r.S.length - 1;

                int j = argMin(r.F[fila]);

                int personas = r.D[fila][j];

                int recursos =
                    e.usaRecursos ? personas / e.operariosPorRecurso : 0;

                double tiempo;

                if(!e.usaRecursos){
                    // secado
                    tiempo = e.tiempo + macetas - 1;
                }else{
                    if(e.tiempoEsTotal){
                        tiempo = e.tiempo / Math.max(1,recursos);
                    }else{
                        tiempo = (macetas * e.tiempo) / Math.max(1,recursos);
                    }
                }

                tabla[k][0] = e.nombre;
                tabla[k][1] = personas;
                tabla[k][2] = recursos;
                tabla[k][3] = String.format("%.2f", tiempo);

                sumaPersonas += personas;
                sumaTiempo += tiempo;
            }

            // fila TOTAL
            tabla[n][0] = "TOTAL";
            tabla[n][1] = sumaPersonas;
            tabla[n][2] = "";
            tabla[n][3] = String.format("%.2f", sumaTiempo);

            return tabla;
        }

        private int buscar(int[] a,int v){
            for(int i=0;i<a.length;i++)
                if(a[i]==v) return i;
            return -1;
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        spOperarios = new javax.swing.JSpinner();
        spMacetas = new javax.swing.JSpinner();
        jPanel6 = new javax.swing.JPanel();
        tabs = new javax.swing.JTabbedPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 51));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("INGRESA LOS PARAMETROS PARA CADA ETAPA");

        btnCalcular.setBackground(new java.awt.Color(14, 57, 14));
        btnCalcular.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(112, 221, 104));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51), null, null));
        jPanel7.setForeground(new java.awt.Color(113, 210, 103));

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel14.setText("Numero de operarios:");

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel15.setText("Numero de macetas a producir:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spOperarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spMacetas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(spOperarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spMacetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(76, 192, 68));

        tabs.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jButton1.setText("CAMBIAR PARAMETROS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jLabel7)
                .addGap(88, 343, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173)
                .addComponent(jButton1)
                .addGap(227, 227, 227))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
            int minDesmolde = 2;
        int minSecado = 0;
        int minMezcla = 2;
        int minEngrase = 1;
        int minMedicion = 2;
        int minTriturado = 2;
        
        int[] mins = {
            minDesmolde,
            minSecado,
            minMezcla,
            minEngrase,
            minMedicion,
            minTriturado
        };
        
        int total = (int) spOperarios.getValue();
        
        int minGlobal =
            minDesmolde +
            minSecado +
            minMezcla +
            minEngrase +
            minMedicion +
            minTriturado;

        if(total < minGlobal){
            javax.swing.JOptionPane.showMessageDialog(this,
                "No existen suficientes operarios para cubrir los mínimos técnicos.\n" +
                "Mínimo requerido: " + minGlobal,
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int libres = total - minGlobal;

        // operarios por recurso (fijos)
        int opMolde = 2;
        int opBowl = 2;
        int opBalanza = 2;
        int opTrituradora = 2;

        // recursos deducidos
        int moldesDesmolde = 1 + libres/opMolde;
        int bowls = 1 + libres/opBowl;
        int balanzas = 1 + libres/opBalanza;
        int trituradoras = 1 + libres/opTrituradora;

        // engrase usa moldes
        int moldesEngrase = moldesDesmolde;
        
        // ================= LIMITES FISICOS (CAPACIDAD REAL) =================
        // Máximo de PERSONAS que realmente pueden trabajar en esa etapa,
        // según recursos disponibles y operarios por recurso.

        int capDesmolde = moldesDesmolde * opMolde;        // 2 por molde
        int capMezcla   = bowls * opBowl;                  // 2 por bowl
        int capMedicion = balanzas * opBalanza;            // 2 por balanza
        int capTriturado = trituradoras * opTrituradora;   // 2 por trituradora
        int capEngrase  = moldesEngrase;                   // 1 por molde (engrase)

        // Smin acumulado
        int acum = 0;

        int smin1 = acum += mins[0];
        int smax1 = total - sumaPosteriores(mins,0);

        int smin2 = acum += mins[1];
        int smax2 = total - sumaPosteriores(mins,1);

        int smin3 = acum += mins[2];
        int smax3 = total - sumaPosteriores(mins,2);

        int smin4 = acum += mins[3];
        int smax4 = total - sumaPosteriores(mins,3);

        int smin5 = acum += mins[4];
        int smax5 = total - sumaPosteriores(mins,4);

        // Triturado: S fijo = total
        int smin6 = total;
        int smax6 = total;
        
        
        tabs.removeAll();

        // ================= DATOS GENERALES =================
        int macetas = (int) spMacetas.getValue();
        double refMacetas = 20.0;   // del experimento
        double tTrituradoUnit = 36.0 / refMacetas;
        double tDes = 0.18 * macetas;
        double tMez = 1.32 * macetas;
        double tEng = 0.25 * macetas;
        double tMed = 1.17 * macetas;
        double tTri = tTrituradoUnit * macetas;

        double tiempoSecado = 17;
        double tSec = tiempoSecado + macetas - 1;
        
        double T = Math.max(tSec,
        Math.max(tTri,
        Math.max(tMed,
        Math.max(tEng,tMez))));


        

        // ================= MOTOR =================
        MotorAsignacion motor = new MotorAsignacion(macetas);

        // ================= ETAPAS =================
        Etapa desmolde =
        new Etapa("Desmolde",0.18,2,moldesDesmolde,true,false);

        Etapa secado =
            new Etapa("Secado",tiempoSecado,0,0,false,true);

        Etapa mezcla =
            new Etapa("Mezcla",1.32,2,bowls,true,false);

        Etapa engrase =
            new Etapa("Engrase",0.25,1,moldesEngrase,true,false);

        Etapa medicion =
            new Etapa("Medicion",1.17,2,balanzas,true,false);

        Etapa triturado =
            new Etapa("Triturado", tTrituradoUnit, opTrituradora, trituradoras, true, false);

        // ================= RESOLUCION =================

        // Estos rangos S son los del PDF (luego los automatizamos)

        ResultadoEtapa[] rs = new ResultadoEtapa[6];

            rs[0] = motor.resolver(desmolde,smin1,smax1,null);
            tabs.addTab("Desmolde", new JScrollPane(crearTabla(rs[0])));

            rs[1] = motor.resolver(secado,smin2,smax2,rs[0]);
            tabs.addTab("Secado", new JScrollPane(crearTabla(rs[1])));

            rs[2] = motor.resolver(mezcla,smin3,smax3,rs[1]);
            tabs.addTab("Mezcla", new JScrollPane(crearTabla(rs[2])));

            rs[3] = motor.resolver(engrase,smin4,smax4,rs[2]);
            tabs.addTab("Engrase", new JScrollPane(crearTabla(rs[3])));

            rs[4] = motor.resolver(medicion,smin5,smax5,rs[3]);
            tabs.addTab("Medicion", new JScrollPane(crearTabla(rs[4])));
            
            int totalOperarios = (int) spOperarios.getValue();

            rs[5] = motor.resolver(triturado,totalOperarios,totalOperarios,rs[4]);
            tabs.addTab("Triturado", new JScrollPane(crearTabla(rs[5])));
            
        String[] nombres = {
            "Desmolde",
            "Secado",
            "Mezcla",
            "Engrase",
            "Medicion",
            "Triturado"
        };

        Etapa[] info = {
            desmolde,
            secado,
            mezcla,
            engrase,
            medicion,
            triturado
        };

        Object[][] interp = interpretar(rs, info, macetas);

        javax.swing.JTable tInterp = new javax.swing.JTable(
            interp,
            new String[]{"Etapa","Personas","Recursos","Tiempo"}
        );

        tabs.addTab("Interpretacion", new JScrollPane(tInterp));
        
        int usados =
            moldesDesmolde * opMolde +
            bowls * opBowl +
            1 +                     // engrase fijo
            balanzas * opBalanza +
            trituradoras * opTrituradora;

        int ociosos = totalOperarios - usados;

        if(ociosos > 0){
            javax.swing.JOptionPane.showMessageDialog(this,
                "Operarios ociosos: " + ociosos +
                "\n(Cuello de botella por recursos físicos)");
        }

    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ventana().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSpinner spMacetas;
    private javax.swing.JSpinner spOperarios;
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables
}
